#!/usr/bin/env bash
#Install nginx web server
apt-get -y update
apt-get -y install nginx
sudo chown -R ubuntu:ubuntu /var/www
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start

