#!/usr/bin/env bash
# install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R ubuntu:ubuntu /var/www
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart

