#!/usr/bin/env bash
# advanced scrip
mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default 
service nginx start
