#!/usr/bin/env bash
# Bash script that creates the file
echo $$ >> /var/run/holbertonscript.pid
while true
do
echo "To infinity and beyond"
sleep 2
trap 'echo I hate the kill command' SIGTERM
trap 'echo Y U no love me?!' SIGINT
trap 'rm /var/run/holbertonscript.pid' SIGQUIT || SIGTERM
done
