#!/usr/bin/env bash
x=1
while [ $x -le 10 ]
do
  x=$(( x + 1 ))
  if [ $x == 5 ]
  then
    echo "bad luck"
  elif [ $x == 9 ]
  then
    echo "good luck"
  else
    echo "Holberton School"
  fi
done
