#!/usr/bin/env bash
if [ -f $"holbertonschool" ]; then
  echo "holbertonschool file exists"
  if [ -s $"holbertonschool" ]
then
     echo "File not empty"
else
     echo "File empty"
  fi
  if [ -f $"holbertonschool" ]; then
   echo "holbertonschool is a regular file"
   fi
else
  echo "holbertonschool file does not exist"
fi
